import type { AppState } from './types';

export const medicineImage =
  'https://images.unsplash.com/photo-1587854692152-cbe660dbde0b?w=200&h=200&fit=crop';

export const initialState: AppState = {
  user: {
    name: 'Demo User',
    email: 'demo@medhome.local',
    role: 'Host',
    authProvider: 'guest',
    household: 'Test Family',
    calendarConnected: false,
  },
  members: [
    {
      id: 'member-1',
      name: 'John Smith',
      role: 'Father',
      age: 55,
      gender: 'Male',
      image: 'https://ui-avatars.com/api/?name=John+Smith&background=0D8ABC&color=fff',
      healthNotes: ['High Blood Pressure', 'Type 2 Diabetes'],
      knownAllergies: 'Penicillin',
    },
    {
      id: 'member-2',
      name: 'Sarah Smith',
      role: 'Mother',
      age: 52,
      gender: 'Female',
      image: 'https://ui-avatars.com/api/?name=Sarah+Smith&background=0D8ABC&color=fff',
      healthNotes: ['Thyroid Issues', 'Seasonal Allergies'],
      knownAllergies: 'None known',
    },
    {
      id: 'member-3',
      name: 'Emma Smith',
      role: 'Daughter',
      age: 24,
      gender: 'Female',
      image: 'https://ui-avatars.com/api/?name=Emma+Smith&background=0D8ABC&color=fff',
      healthNotes: ['Asthma'],
      knownAllergies: 'Aspirin',
    },
    {
      id: 'member-4',
      name: 'Robert Smith',
      role: 'Grandfather',
      age: 78,
      gender: 'Male',
      image: 'https://ui-avatars.com/api/?name=Robert+Smith&background=0D8ABC&color=fff',
      healthNotes: ['Arthritis', 'Low Vision'],
      knownAllergies: 'Sulfonamides',
    },
  ],
  medicines: [
    {
      id: 'med-1',
      name: 'Lisinopril',
      category: 'Prescription',
      strength: '10mg',
      type: 'Tablet',
      quantity: 28,
      unit: 'tablets',
      assignedToId: 'member-1',
      expiryDate: '2025-12-31',
      manufactureDate: '2023-06-15',
      pharmaName: 'CVS Pharmacy',
      use: 'Blood pressure management',
      dosage: '1 tablet',
      mealInstruction: 'Once daily, morning',
      reminderTimes: ['08:00'],
      lowStockAt: 10,
      image: medicineImage,
    },
    {
      id: 'med-2',
      name: 'Metformin',
      category: 'Prescription',
      strength: '500mg',
      type: 'Tablet',
      quantity: 60,
      unit: 'tablets',
      assignedToId: 'member-1',
      expiryDate: '2025-08-20',
      manufactureDate: '2023-02-10',
      pharmaName: 'Walgreens',
      use: 'Diabetes control',
      dosage: '1 tablet twice daily',
      mealInstruction: 'With meals',
      reminderTimes: ['08:00', '20:00'],
      lowStockAt: 20,
      image: medicineImage,
    },
    {
      id: 'med-3',
      name: 'Levothyroxine',
      category: 'Prescription',
      strength: '50mcg',
      type: 'Tablet',
      quantity: 30,
      unit: 'tablets',
      assignedToId: 'member-2',
      expiryDate: '2026-03-10',
      manufactureDate: '2024-03-11',
      pharmaName: 'Target Pharmacy',
      use: 'Thyroid hormone replacement',
      dosage: '1 tablet',
      mealInstruction: 'On empty stomach, 30 mins before breakfast',
      reminderTimes: ['07:00'],
      lowStockAt: 10,
      image: medicineImage,
    },
    {
      id: 'med-4',
      name: 'Albuterol Inhaler',
      category: 'Prescription',
      strength: '90mcg',
      type: 'Inhaler',
      quantity: 2,
      unit: 'inhalers',
      assignedToId: 'member-3',
      expiryDate: '2025-09-30',
      manufactureDate: '2023-09-29',
      pharmaName: 'CVS Pharmacy',
      use: 'Asthma relief',
      dosage: '2 puffs as needed',
      mealInstruction: 'As needed for breathing difficulty',
      reminderTimes: [],
      lowStockAt: 1,
      image: medicineImage,
    },
    {
      id: 'med-5',
      name: 'Vitamin D3',
      category: 'OTC',
      strength: '1000IU',
      type: 'Tablet',
      quantity: 3,
      unit: 'bottles',
      assignedToId: 'member-4',
      expiryDate: '2025-11-15',
      manufactureDate: '2023-11-14',
      pharmaName: 'Amazon',
      use: 'Bone health support',
      dosage: '1 tablet',
      mealInstruction: 'With breakfast',
      reminderTimes: ['08:30'],
      lowStockAt: 2,
      image: medicineImage,
    },
    {
      id: 'med-6',
      name: 'Aspirin',
      category: 'OTC',
      strength: '325mg',
      type: 'Tablet',
      quantity: 8,
      unit: 'tablets',
      assignedToId: 'member-1',
      expiryDate: '2025-06-20',
      manufactureDate: '2023-06-19',
      pharmaName: 'CVS Pharmacy',
      use: 'Pain relief and heart health',
      dosage: '1 tablet',
      mealInstruction: 'With food',
      reminderTimes: [],
      lowStockAt: 10,
      image: medicineImage,
    },
    {
      id: 'med-7',
      name: 'Cetirizine',
      category: 'OTC',
      strength: '10mg',
      type: 'Tablet',
      quantity: 15,
      unit: 'tablets',
      assignedToId: 'member-2',
      expiryDate: '2026-02-28',
      manufactureDate: '2024-02-27',
      pharmaName: 'Walgreens',
      use: 'Allergy relief',
      dosage: '1 tablet',
      mealInstruction: 'Once daily, evening',
      reminderTimes: ['21:00'],
      lowStockAt: 5,
      image: medicineImage,
    },
    {
      id: 'med-8',
      name: 'Ibuprofen',
      category: 'OTC',
      strength: '200mg',
      type: 'Tablet',
      quantity: 20,
      unit: 'tablets',
      assignedToId: 'member-4',
      expiryDate: '2025-10-10',
      manufactureDate: '2023-10-09',
      pharmaName: 'CVS Pharmacy',
      use: 'Pain and inflammation relief',
      dosage: '1-2 tablets',
      mealInstruction: 'With food or milk',
      reminderTimes: [],
      lowStockAt: 10,
      image: medicineImage,
    },
  ],
  reminderLogs: [
    {
      id: 'reminder-1',
      medicineId: 'med-1',
      memberId: 'member-1',
      time: '08:00',
      status: 'taken',
      takenAt: new Date().toISOString(),
    },
    {
      id: 'reminder-2',
      medicineId: 'med-2',
      memberId: 'member-1',
      time: '08:00',
      status: 'taken',
      takenAt: new Date().toISOString(),
    },
    {
      id: 'reminder-3',
      medicineId: 'med-2',
      memberId: 'member-1',
      time: '20:00',
      status: 'upcoming',
    },
    {
      id: 'reminder-4',
      medicineId: 'med-3',
      memberId: 'member-2',
      time: '07:00',
      status: 'missed',
    },
    {
      id: 'reminder-5',
      medicineId: 'med-4',
      memberId: 'member-3',
      time: '10:00',
      status: 'upcoming',
    },
    {
      id: 'reminder-6',
      medicineId: 'med-5',
      memberId: 'member-4',
      time: '08:30',
      status: 'taken',
      takenAt: new Date().toISOString(),
    },
    {
      id: 'reminder-7',
      medicineId: 'med-7',
      memberId: 'member-2',
      time: '21:00',
      status: 'upcoming',
    },
    {
      id: 'reminder-8',
      medicineId: 'med-1',
      memberId: 'member-1',
      time: '08:00',
      status: 'upcoming',
    },
  ],
  caregivers: [
    {
      id: 'caregiver-1',
      name: 'Dr. Michael Johnson',
      relationship: 'Primary Care Physician',
      accessLevel: 'Read-Only',
      status: 'Active',
    },
    {
      id: 'caregiver-2',
      name: 'Lisa Anderson',
      relationship: 'Nurse',
      accessLevel: 'Reminder Access',
      status: 'Active',
    },
  ],
};
